### ISSUE TITLE
rework user input validation

### ISSUE THREAD

**Issue by drzraf** [wp-cli/export-command#18] opened 2017-09-01 21:20 UTC
Main issues:
* order of application of arguments is random:
Ex: check of mutual exclusion or mutual incompatibility does not fit well into the model of independant validators

* can't check raw user input but only the result of the merge of user input + default values
So can't check if a value is the result of explicit user input or the result of default whose distinction is sometimes required

**Comment by schlessera** [comment] 2017-09-04 20:12
@drzraf Can you be more specific about what specific use case you're referring to/what specific problem you're trying to solve? Did you hit a specific case where the current mechanism caused a blocking issue?

Note: I'm not saying that the user input validation is without flaws. But we're trying to be pragmatic about what parts of the code to refactor, and we don't want rewrite code (and potentially cause breaking changes and bugs) just for the sake of it.

**Comment by drzraf** [comment] 2017-09-05 02:13
1) https://github.com/wp-cli/export-command/blob/master/src/Export_Command.php#L202
```
		foreach ( $args as $key => $value ) {
			if ( is_callable( array( $this, 'check_' . $key ) ) ) {
				$result = call_user_func( array( $this, 'check_' . $key ), $value );
```

If one wants to ensure that `--stdout` has not been set with `--dir=` being set too, neither the loop nor individual `check_*` are the right place.

2) https://github.com/wp-cli/export-command/blob/master/src/Export_Command.php#L126
```
		if (! empty( $assoc_args['stdout'] ) && ( ! empty( $assoc_args['dir'] ) || ! empty( $assoc_args['filename_format'] ) ) ) {
			WP_CLI::error( '--stdout and --dir cannot be used together.' );
		}
		$assoc_args = wp_parse_args( $assoc_args, $defaults );
```

After `wp_parse_args()` there are no more possibility to check whether `stdout` is the result of default or the result of user input.

In the current code, both of these two important mechanisms (both related to input handling and  mutual option combination) can't find there place in the "standard" codepath.

I'm opening this bug in prevision that increasing introduction command line options that may sooner or later leaves the input validation routine more and more messy.

**Comment by schlessera** [comment] 2017-09-05 14:53
For 1., you can easily add another check either in front or after the loop. These `check_*` methods are meant to check individual arguments as they make sense. As what you want to check is an interaction between two different arguments, it will of course not fit into this pattern. However, these `check_*` methods are to be seen as helpers only. The responsibility of the validation resides with the overarching `validate_args()` method, and you can add whatever other patterns/helpers you need in there.

For 2., this seems like a theoretical problem only to me, as you should already know what arguments are part of the defaults, as these defaults are set by the code as well. And you could argue that the rest of the code should not even be capable of making that distinction.

So, again, yes, I agree that this is not as clean as it could be. But the current code seems to work and solve all problems it encounters to satisfaction, unless I misunderstood your examples.

As well, the issue you're discussing is not a bug of the `export-command` package, so I'd suggest opening an enhancement suggestion in [`wp-cli/ideas`](https://github.com/wp-cli/ideas/issues) instead to (in the long-term) discuss a potential next implementation of user input validation in general.

**Comment by schlessera** [comment] 2017-09-05 14:55
I'll close this off as the issue is not specific to this single package, and should be discussed in `wp-cli/ideas` as a potential future enhancement instead.

**Closed by schlessera** 2017-09-05 14:55 UTC
